use_frameworks!

target 'Marker_Example', :exclusive => true do
  pod 'Marker', :path => '../'
end

target 'Marker_Tests', :exclusive => true do
  pod 'Marker', :path => '../'

  pod 'FBSnapshotTestCase'
end
